# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Kalani - J352
tagline:          'University of Maryland'
description:      'Course material for J352 at UMD'
url:              https://umd-kalani.github.io/
baseurl:          /

author:
  name:           'Kalani Gordon'
  url:            https://twitter.com/kalanigordon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
